openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://www.sudoc.fr/
info:
  description: |
    Produit des notices TEI à partir de notices de documents universitaires au format [MarcXML](http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#SudocMarcXML). Ces notices peuvent être importées dans HAL grâce à [SWORD](https://api.archives-ouvertes.fr/docs/sword) ou [X2hal](https://doc.archives-ouvertes.fr/x2hal/).
  version: "1.0.0"
  title: MarcXML2TEI
  contact:
    email: no-reply@abes.fr
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /{ppn}.tei:
    parameters:
    - in: path
      name: ppn
      schema:
        type: string
        pattern: '^\d{8}(X|\d)$'
      required: true
      example: "252383524"
      description: PPN de la notice Sudoc
    get:
      summary: Transforme une notice Sudoc en TEI
      operationId: MarcXML2TEI
      description: |
        Transforme une notice Sudoc en TEI
        
        Seule les notices conformes aux règles de catalogage des [travaux universitaires hors thèses](http://documentation.abes.fr/sudoc/regles/Catalogage/Regles_Theses_AutresDocsUniv.htm) peuvent être transformées au format TEI.

      responses:
        '404':
          description: La ressource demandée ou le PPN n'existent pas
          content:
            text/html:
              schema:
                type: string
              example: |
                <html>
                  <head>
                    <title>404 Not Found</title>
                  </head>
                  <body>
                    <h1>Not Found</h1>
                    <p>The requested URL /252383524.tei was not found on this server.</p>
                  </body>
                </html>
        '200':
          description: Succès de la transformation
          content:
            application/xml:
              schema:
                xml:
                  name: TEI
                type: object
                example: |
                  <TEI xmlns="http://www.tei-c.org/ns/1.0"
                    xmlns:ext="http://exslt.org/common"
                    xmlns:hal="http://hal.archives-ouvertes.fr/"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.tei-c.org/ns/1.0 http://api.archives-ouvertes.fr/documents/aofr-sword.xsd">
                    <text>
                      <body>
                        <listBibl>
                          <biblFull>
                            <editionStmt>
                              <edition>
                                <date type="whenWritten">2020</date>
                              </edition>
                            </editionStmt>
                            <notesStmt>
                              <note type="audience" n="3"/>
                              <note type="degree" n="23"/>
                            </notesStmt>
                            <sourceDesc>
                              <biblStruct>
                                <analytic>
                                  <title xml:lang="fr">La longévité politique : être et rester un élu de la République. L’exemple d’Amédée Bouquerel, sénateur de l’Oise de 1948 à 1992</title>
                                  <author role="aut">
                                    <persName>
                                      <forename type="first">Carpi</forename>
                                        <surname>Benjamin</surname>
                                      </persName>
                                    <idno type="IdRef">https://www.idref.fr/252385659</idno>
                                  </author>
                                </analytic>
                                <monogr>
                                  <imprint>
                                    <biblScope unit="pp">183</biblScope>
                                    <date type="dateDefended">2020-01-01</date>
                                  </imprint>
                                  <authority type="supervisor">David Bellamy</authority>
                                </monogr>
                              </biblStruct>
                            </sourceDesc>
                            <profileDesc>
                              <langUsage>
                                <language ident="fr"/>
                              </langUsage>
                              <textClass>
                                <keywords scheme="author">
                                  <term xml:lang="fr">Gaullisme</term>
                                  <term xml:lang="fr">France</term>
                                </keywords>
                                <classCode scheme="halTypology" n="MEM"/>
                              </textClass>
                              <abstract xml:lang="fr">Lorem ipsum dolor sit amet</abstract>
                              <abstract xml:lang="en">Lorem ipsum dolor sit amet</abstract>
                              </profileDesc>
                            </biblFull>
                          </listBibl>
                        </body>
                      </text>
                    </TEI>
