name: Release

on:
  push:
    tags:
      - "v*" # Seulement pour les versions

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils libsaxon-java default-jre
          make install-saxon
          make install-xspec
      - name: Run tests
        run: |
          export SAXON_CP=/tmp/saxon/saxon9he.jar
          make full-tests
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bundle/marcxml2tei-1.0.xsl
            bundle/marcxml2tei-oracle.xsl
            utils/oracle-cleaner.xsl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
